name: Proceso Integracion Continua

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Descargar software del repositorio
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Dar permisos al wrapper de Maven
        run: chmod +x mvnw

      - name: Compilar y empaquetar
        run: ./mvnw --batch-mode -DskipTests package

      - name: Ejecutar pruebas automatizadas
        run: ./mvnw --batch-mode verify

      - name: Generar reporte de resultados de pruebas
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'

      - name: Generar un reporte de cobertura de pruebas
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: 'target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          github_token: ${{ secrets.GITHUB_TOKEN }}
